#!/bin/bash

function usage() {
    echo "Usage: arch-pkg [install|remove|update] [package manager] [package name]"
    exit 1
}

if [[ $# -ne 3 ]]; then
    usage
fi

command=$1
manager=$2
package=$3

case $manager in
    pacman)
        case $command in
            install)
                sudo pacman -S $package
                ;;
            remove)
                sudo pacman -R $package
                ;;
            update)
                sudo pacman -Syu
                ;;
            *)
                usage
                ;;
        esac
        ;;
    flatpak)
        case $command in
            install)
                flatpak install $package
                ;;
            remove)
                flatpak uninstall $package
                ;;
            update)
                flatpak update $package
                ;;
            *)
                usage
                ;;
        esac
        ;;
    yay)
        case $command in
            install)
                yay -S $package
                ;;
            remove)
                yay -R $package
                ;;
            update)
                yay -Syu
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac

exit 0
