#!/bin/bash

if [ "$1" = "install" ]; then
    pacman -S "$2"
    yay -S "$2"
elif [ "$1" = "remove" ]; then
    pacman -R "$2"
    yay -R "$2"
if [ "$1" = "update" ]; then
    pacman -U "$2"
    yay -U "$2"
else
    echo "Usage: $0 [install|remove|update] package"
fi
