#!/bin/bash

function usage() {
    echo "Usage: arch-pkg [install|remove|update|search|list] [package manager] [package name]"
    exit 1
}

if [[ $# -lt 2 ]]; then
    usage
fi

command=$1
manager=$2
package=$3

case $manager in
    pacman)
        case $command in
            install)
                sudo pacman -S $package
                ;;
            remove)
                sudo pacman -R $package
                ;;
            update)
                sudo pacman -Syu
                ;;
            search)
                if [[ -n $package ]]; then
                    sudo pacman -Q $package
                else
                    sudo pacman -Q
                fi
                ;;
            list)
                sudo pacman -Qe
                ;;
            *)
                usage
                ;;
        esac
        ;;
    flatpak)
        case $command in
            install)
                flatpak install $package
                ;;
            remove)
                flatpak uninstall $package
                ;;
            update)
                flatpak update $package
                ;;
            search)
                if [[ -n $package ]]; then
                    flatpak search $package
                else
                    flatpak search
                fi
                ;;
            list)
                flatpak list
                ;;
            *)
                usage
                ;;
        esac
        ;;
    yay)
        case $command in
            install)
                yay -S $package
                ;;
            remove)
                yay -R $package
                ;;
            update)
                yay -Syu
                ;;
            search)
                if [[ -n $package ]]; then
                    yay -Q $package
                else
                    yay -Q
                fi
                ;;
            list)
                yay -Qe
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac

exit 0
